import type { ChildProcess } from 'node:child_process'
import { spawn } from 'node:child_process'
import * as fs from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * Cherry Chat macOS arm64 build wrapper (Phase B / P-B, finding F1).
 *
 * The flavor build runs `generate:openapi` before electron-vite and
 * electron-builder, which regenerates the TRACKED
 * `src/main/apiServer/generated/openapi-spec.json` with Cherry Chat metadata
 * (IDENTITY-002). That generated content must reach the packaged app (the
 * builder consumes the build output), but the working tree must keep the
 * tracked default spec byte-for-byte (IDENTITY-001).
 *
 * This wrapper snapshots the tracked spec before the build and restores the
 * exact original bytes in a `finally` path after BOTH the build phase and the
 * packaging phase have run — on success and on any failure. Cleanup is
 * structured Node child-process execution (no shell `trap`), inherits
 * stdio/environment, and preserves exit-code / signal failure semantics. The
 * snapshot lives in memory only: no temp files are left in the repository and
 * no secret material is copied anywhere.
 */

const CURRENT_FILE = fileURLToPath(import.meta.url)
const REPO_ROOT = path.resolve(path.dirname(CURRENT_FILE), '..')

export const CHERRY_CHAT_FLAVOR = 'cherry-chat'

/** Environment keys the wrapper must inject into every child step. */
export const CHERRY_CHAT_FLAVOR_ENV: Readonly<Record<string, string>> = {
  VITE_APP_FLAVOR: CHERRY_CHAT_FLAVOR
}

/** The tracked spec regenerated by `generate:openapi` during a flavor build. */
export const OPENAPI_SPEC_RELATIVE_PATH = 'src/main/apiServer/generated/openapi-spec.json'

export interface SpawnStep {
  command: string
  args: string[]
}

/**
 * The two sequential phases of the Cherry Chat macOS arm64 build, mirroring the
 * historical `build:chat:mac:arm64` chain exactly: flavor-aware generation +
 * electron-vite build first, then the macOS arm64 builder against the overlay.
 */
export const BUILD_STEPS: readonly SpawnStep[] = [
  { command: 'dotenv', args: ['npm', 'run', 'build'] },
  { command: 'electron-builder', args: ['--config', 'electron-builder.cherry-chat.yml', '--mac', '--arm64'] }
]

export interface RunStepContext {
  command: string
  args: string[]
  env: NodeJS.ProcessEnv
  cwd: string
}

export type RunStep = (ctx: RunStepContext) => Promise<void>

export interface RunChatBuildOptions {
  /** Repository root; defaults to the repo containing this script. */
  repoRoot?: string
  /** Steps to run sequentially; defaults to {@link BUILD_STEPS}. */
  steps?: readonly SpawnStep[]
  /** Step executor; defaults to the real structured spawn. */
  runStep?: RunStep
  /** Base env to inherit; defaults to `process.env`. */
  baseEnv?: NodeJS.ProcessEnv
  /** Spec path relative to `repoRoot`. */
  openapiRelativePath?: string
}

/** The inherited environment plus the locked flavor key (IDENTITY-002). */
export function buildStepEnv(baseEnv: NodeJS.ProcessEnv): NodeJS.ProcessEnv {
  return { ...baseEnv, ...CHERRY_CHAT_FLAVOR_ENV }
}

/** Resolve a repo-local `node_modules/.bin` executable (macOS/Linux). */
export function resolveBin(command: string, repoRoot: string): string {
  const local = path.join(repoRoot, 'node_modules', '.bin', command)
  if (fs.existsSync(local)) {
    return local
  }
  // Fall back to PATH lookup; a missing binary surfaces as the spawn ENOENT.
  return command
}

type Snapshot = { existed: true; bytes: Buffer } | { existed: false; bytes: undefined }

function snapshotFile(specPath: string): Snapshot {
  try {
    return { existed: true, bytes: fs.readFileSync(specPath) }
  } catch {
    return { existed: false, bytes: undefined }
  }
}

function restoreFile(specPath: string, snapshot: Snapshot): void {
  if (snapshot.existed) {
    fs.writeFileSync(specPath, snapshot.bytes)
  } else {
    fs.rmSync(specPath, { force: true })
  }
}

/**
 * Run the flavor build + packaging phases and ALWAYS restore the tracked spec
 * afterwards, whether the chain succeeded or a step failed. The step order is
 * preserved (build phase before builder phase) and every step receives the
 * cherry-chat flavor in its environment.
 */
export async function runChatMacArm64Build(options: RunChatBuildOptions = {}): Promise<void> {
  const repoRoot = options.repoRoot ?? REPO_ROOT
  const specPath = path.join(repoRoot, options.openapiRelativePath ?? OPENAPI_SPEC_RELATIVE_PATH)
  const snapshot = snapshotFile(specPath)
  const runStep = options.runStep ?? runStepReal
  let failure: unknown = null

  try {
    for (const step of options.steps ?? BUILD_STEPS) {
      await runStep({
        command: step.command,
        args: [...step.args],
        env: buildStepEnv(options.baseEnv ?? process.env),
        cwd: repoRoot
      })
    }
  } catch (err) {
    failure = err
  } finally {
    restoreFile(specPath, snapshot)
  }

  if (failure !== null) {
    throw failure
  }
}

/**
 * Real step executor: structured child-process spawn with inherited stdio and
 * env. Exit codes and signal terminations are surfaced so the wrapper preserves
 * the exact failure semantics of the underlying build command.
 */
function runStepReal({ command, args, env, cwd }: RunStepContext): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(resolveBin(command, cwd), args, { stdio: 'inherit', env, cwd })
    activeChild = child
    let settled = false

    const fail = (err: Error): void => {
      if (settled) {
        return
      }
      settled = true
      activeChild = null
      reject(err)
    }

    child.once('error', (err) => {
      fail(err)
    })

    child.once('exit', (code, signal) => {
      if (settled) {
        return
      }
      settled = true
      activeChild = null
      if (signal) {
        const err = new Error(`'${command}' was terminated by signal ${signal}`) as Error & { signal?: string | null }
        err.signal = signal
        reject(err)
      } else if (code === 0) {
        resolve()
      } else {
        const err = new Error(`'${command}' failed with exit code ${code}`) as Error & { code?: number }
        err.code = code ?? undefined
        reject(err)
      }
    })
  })
}

// ---------------------------------------------------------------------------
// CLI entry (only when executed directly, like scripts/generate-openapi-spec.ts)
// ---------------------------------------------------------------------------

/** Signals that defer immediate exit so the finally-restore can run. */
const DEFERRED_SIGNALS = ['SIGINT', 'SIGTERM', 'SIGHUP'] as const
let pendingSignal: NodeJS.Signals | null = null
let activeChild: ChildProcess | null = null

function signalExitCode(signal: NodeJS.Signals): number {
  const number = os.constants.signals[signal]
  return 128 + (typeof number === 'number' ? number : 0)
}

/** Re-raise the signal after cleanup so the parent shell sees the same exit. */
function reRaise(signal: NodeJS.Signals): void {
  for (const name of DEFERRED_SIGNALS) {
    process.removeAllListeners(name)
  }
  process.kill(process.pid, signal)
  process.exitCode = signalExitCode(signal)
}

const isMainScript = process.argv[1] != null && path.resolve(process.argv[1]) === CURRENT_FILE

if (isMainScript) {
  // Defer termination on interactive signals (Ctrl+C, kill) until the tracked
  // spec has been restored; the active child (same process group) receives the
  // signal too, so its exit surfaces as the step failure that unwinds through
  // the finally path.
  for (const name of DEFERRED_SIGNALS) {
    process.on(name, () => {
      pendingSignal = name
      activeChild?.kill(name)
    })
  }

  runChatMacArm64Build()
    .then(() => {
      if (pendingSignal) {
        reRaise(pendingSignal)
        return
      }
      process.exitCode = 0
    })
    .catch((err: unknown) => {
      const signal = (err as { signal?: unknown }).signal
      if (typeof signal === 'string' && signal) {
        reRaise(signal as NodeJS.Signals)
        return
      }
      const code = (err as { code?: unknown }).code
      process.exitCode = typeof code === 'number' ? code : 1
    })
}
